---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: gitea.weakptr.site/weakptr/docker:dind
  when:
    event: 
      - push
  environment:
    AUTH:
      from_secret: docker_config_json
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: deploy_dir
    path: /deploy
  commands:
    - mkdir -p ~/.docker
    - echo $AUTH | tee -a ~/.docker/config.json
    - docker build . -t gitea.weakptr.site/weakptr/blog:ci_${DRONE_BUILD_NUMBER}_${DRONE_COMMIT_SHA:0:8}
    - docker push gitea.weakptr.site/weakptr/blog:ci_${DRONE_BUILD_NUMBER}_${DRONE_COMMIT_SHA:0:8}
    - "sed -i 's|image:[[:space:]]gitea.weakptr.site/weakptr/blog:.*|image: gitea.weakptr.site/weakptr/blog:ci_${DRONE_BUILD_NUMBER}_${DRONE_COMMIT_SHA:0:8}|' /deploy/docker-compose.yaml"
    - "cd /deploy; docker-compose up -d blog"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: deploy_dir
    host:
      path: /ubuntu/repos/my-server

trigger:
  branch: 
    - main
    - dev/*

---
kind: pipeline
type: docker
name: synchronize repository

steps:
  - name: push commits
    image: gitea.weakptr.site/weakptr/bitnami/git:latest
    when:
      event: 
        - push
    environment:
      PRIVATE_KEY:
        from_secret: ssh_private_key
      KNOWN_HOSTS:
        from_secret: ssh_known_hosts
    commands:
      - mkdir -p ~/.ssh
      - chmod 750 ~/.ssh
      - echo "$PRIVATE_KEY" | tee -a ~/.ssh/id_ed25519
      - ssh-keyscan -H github.com | tee -a ~/.ssh/known_hosts
      - chmod 600 ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/known_hosts
      - git remote set-url origin git@github.com:nnnewb/blog.git
      - git push origin $DRONE_BRANCH
