---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind
  environment:
    AUTH:
      from_secret: docker_config_json
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - mkdir -p ~/.docker
    - echo $AUTH | tee -a ~/.docker/config.json
    - docker build . -t gitea.weakptr.site/weakptr/blog:1.0.0
    - docker push gitea.weakptr.site/weakptr/blog:1.0.0

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch: 
    - main
