---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind
  settings:
    auth:
      from_secret: docker_config_json
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - echo $AUTH > ~/.docker/config.json
    - docker build . -t gitea.weakptr.site/weakptr/blog:1.0.0
    - docker push gitea.weakptr.site/weakptr/blog:1.0.0

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
