version: '3.1'
services:
  blog:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/fullchain.pem:/fullchain.pem
      - ./ssl/privkey.pemA:/privkey.pem
      - ./https.conf:/etc/nginx/sites-enabled/default
