version: '3.1'
services:
  blog:
    image: nginx:mainline
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/fullchain.pem:/fullchain.pem
      - ./ssl/privkey.pem:/privkey.pem
      - ./https.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    networks:
      - weakptr_site

networks:
  weakptr_site:
    external: true
