name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: copy template
        with:
          cmd: cp config.tpl.yaml config.yaml

      - name: Adjust customText
        uses: mikefarah/yq@v4.25.1
        with:
          cmd: yq -i '.params.footer.customText = "GitHub Pages"' config.yaml

      - name: Adjust comments enabled
        uses: mikefarah/yq@v4.25.1
        with:
          cmd: yq -i '.params.comments.enabled = "true"' config.yaml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.87.0
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
